### ISSUE TITLE
The Bisection does not work

### ISSUE THREAD

**Issue by dsandber** [teamairship/root_solver#1]
I get something like this when I look at the attempts being generated:

rate: 0.5 ==> sum: -22.899213985885797
rate: 0.75 ==> sum: -31.764147433486965
rate: 0.875 ==> sum: -35.324541486689604
rate: 0.9375 ==> sum: -36.93615049969411
rate: 0.96875 ==> sum: -37.70450144294077
rate: 0.984375 ==> sum: -38.079830291638686
rate: 0.9921875 ==> sum: -38.26534382391253
rate: 0.99609375 ==> sum: -38.35757023765938
rate: 0.998046875 ==> sum: -38.40355176414263
rate: 0.9990234375 ==> sum: -38.426509719911834
rate: 0.99951171875 ==> sum: -38.437980509954485

Note that the attempted value is only going up.  The true minimum is at around 0.1, but it only keeps trying higher numbers!

This is due to this line:

    else #narrow window of searching by half
      if y > 0
        high = x
      else
        low = x
      end

which is definitely not doing what is expected.

**Comment by rthbound** [comment]
@dsandber we'd like to take a look at what's going on in your case. Can you provide us with your inputs?

**Comment by dsandber** [comment]
sorry, I already switched to other bisection code so I don't have the original.  If you think about the code I posted though, it should be fairly obvious that the code won't work right.  It decides whether to look in the bottom or top half-window by looking at whether "y" is positive or not.  This has nothing to do with which half would better minimize the function.

I used code from scipy, something like this:
```
  def solve()
    ax = @lower
    cx = @upper
    k = 0
    fa = 0
    fc = 0
    while (ax-cx).abs > @epsilon and k < @max_iteration
      bx = (ax + cx).quo(2)
      fa = @func.call(ax)
      fb = @func.call(bx)
      fc = @func.call(cx)
      if fa * fb < 0
        cx = bx
      else fb *fc < 0
        ax = bx
      end
      k +=1
    end

    if fa < fc
      @x_minimum,@f_minimum = ax.to_f, @func.call(ax).to_f;
    else
      @x_minimum,@f_minimum = cx.to_f, @func.call(cx).to_f;
    end
  end
```

instead and it worked well.

**Comment by dsandber** [comment]
just noticed the "else fb * fc < 0" is weird, but code seems to work so probably the "fb * fc < 0" is ignored. [there's no "if"]

**Comment by dsandber** [comment]
took the code from sciruby minimization.rb, not scipy.

**Comment by rthbound** [comment]
@dsandber, thanks for pointing this out. @lohannon is addressing this in #2.

**Comment by dsandber** [comment]
Your test function has a minimum at exactly x=0, which is why your existing code seemed to work.  I suggest instead minimizing: (x-1)^2

If you test all three conditions == x=0, x=1, and x=2, and the correct root is return in all cases than your function is probably correct.
